version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ebook_store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebook_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Đã thay đổi từ 8080 -> 8081
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped
  

volumes:
  postgres_data: