version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ebook_store_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-ebook_store}
      TZ: ${TIME_ZONE:-Asia/Ho_Chi_Minh}  # Thêm múi giờ cho DB
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-ebook_store}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-24h}
      SSL_MODE: ${SSL_MODE:-disable}
      MAX_DB_CONN: ${MAX_DB_CONN:-20}
      DEBUG_MODE: ${DEBUG_MODE:-true}
      TZ: ${TIME_ZONE:-Asia/Ho_Chi_Minh}  # Đồng bộ múi giờ
    ports:
      - "${SERVER_PORT:-8081}:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped

volumes:
  postgres_data: